### ISSUE TITLE
Add example for uploading files using curl

### ISSUE THREAD

**Issue by Mindavi** [sgreben/http-file-server#2]
Because this was not as straightforward as I thought it was, I think it would be good to add this to the README.

How to upload files using curl:

```
./http-file-server -uploads /=/path/to/serve
curl -F "file=@example.txt" localhost:8080/path/to/upload/to
```

Alternatively, you could support the `--upload-file` function of curl, which does a PUT request to the new path for the file.

**Comment by sgreben** [comment]
Thank you! I've added this one in https://github.com/sgreben/http-file-server/releases/tag/1.5.2 :)
